/* =============================================
   Project Portfolio Data Template
   Replace sample values with your real projects
============================================= */

export const cardsData = [
  {
    title: "Project Title 1",
    slug: "project-title-1",
    tags: "React, Node.js, MongoDB",
    description: "A full-stack web application for managing tasks.",
    category: "web", // Categories: web | backend | mobile
    images: [
      "./assets/images/sample1.png",
      "./assets/images/sample2.png",
      "./assets/images/sample3.png",
      "./assets/images/sample4.png",
      "./assets/images/sample5.png",
      "./assets/images/sample6.png",
    ],
    links: [
      { url: "#", icon: "fas fa-play-circle" },
      { url: "https://github.com/", icon: "fab fa-github" },
    ],
  },
  {
    title: "Project Title 2",
    slug: "project-title-2",
    tags: "Node.js, Express, PostgreSQL",
    description: "A RESTful API for managing user data.",
    category: "backend",
    images: [
      "./assets/images/sample1.png",
      "./assets/images/sample2.png",
      "./assets/images/sample3.png",
      "./assets/images/sample4.png",
      "./assets/images/sample5.png",
      "./assets/images/sample6.png",
    ],
    links: [
      { url: "#", icon: "fas fa-play-circle" },
      { url: "https://github.com/", icon: "fab fa-github" },
    ],
  },
  {
    title: "Project Title 3",
    slug: "project-title-3",
    tags: "React Native, Firebase",
    description: "A mobile app for fitness tracking and nutrition logs.",
    category: "mobile",
    images: [
      "./assets/images/sample1.png",
      "./assets/images/sample2.png",
      "./assets/images/sample3.png",
      "./assets/images/sample4.png",
      "./assets/images/sample5.png",
      "./assets/images/sample6.png",
    ],
    links: [
      { url: "#", icon: "fas fa-play-circle" },
      { url: "https://github.com/", icon: "fab fa-github" },
    ],
  },
  {
    title: "Project Title 4",
    slug: "project-title-4",
    tags: "Vue.js, Firebase",
    description: "An example web app built with Vue.js and Firebase.",
    category: "web",
    images: [
      "./assets/images/sample1.png",
      "./assets/images/sample2.png",
      "./assets/images/sample3.png",
      "./assets/images/sample4.png",
      "./assets/images/sample5.png",
      "./assets/images/sample6.png",
    ],
    links: [
      { url: "#", icon: "fas fa-play-circle" },
      { url: "https://github.com/", icon: "fab fa-github" },
    ],
  },
  {
    title: "Project Title 5",
    slug: "project-title-5",
    tags: "Django, PostgreSQL",
    description: "A backend service using Django REST framework.",
    category: "backend",
    images: [
      "./assets/images/sample1.png",
      "./assets/images/sample2.png",
      "./assets/images/sample3.png",
      "./assets/images/sample4.png",
      "./assets/images/sample5.png",
      "./assets/images/sample6.png",
    ],
    links: [
      { url: "#", icon: "fas fa-play-circle" },
      { url: "https://github.com/", icon: "fab fa-github" },
    ],
  },
  {
    title: "Project Title 6",
    slug: "project-title-6",
    tags: "Flutter, Firebase",
    description: "A cross-platform mobile app for task management.",
    category: "mobile",
    images: [
      "./assets/images/sample1.png",
      "./assets/images/sample2.png",
      "./assets/images/sample3.png",
      "./assets/images/sample4.png",
      "./assets/images/sample5.png",
      "./assets/images/sample6.png",
    ],
    links: [
      { url: "#", icon: "fas fa-play-circle" },
      { url: "https://github.com/", icon: "fab fa-github" },
    ],
  },
  {
    title: "Project Title 7",
    slug: "project-title-7",
    tags: "Angular, Node.js",
    description: "A web application built with Angular and Node.js.",
    category: "web",
    images: [
      "./assets/images/sample1.png",
      "./assets/images/sample2.png",
      "./assets/images/sample3.png",
      "./assets/images/sample4.png",
      "./assets/images/sample5.png",
      "./assets/images/sample6.png",
    ],
    links: [
      { url: "#", icon: "fas fa-play-circle" },
      { url: "https://github.com/", icon: "fab fa-github" },
    ],
  },
  {
    title: "Project Title 8",
    slug: "project-title-8",
    tags: "Spring Boot, MySQL",
    description: "A backend service using Spring Boot and MySQL.",
    category: "backend",
    images: [
      "./assets/images/sample1.png",
      "./assets/images/sample2.png",
      "./assets/images/sample3.png",
      "./assets/images/sample4.png",
      "./assets/images/sample5.png",
      "./assets/images/sample6.png",
    ],
    links: [
      { url: "#", icon: "fas fa-play-circle" },
      { url: "https://github.com/", icon: "fab fa-github" },
    ],
  },
  {
    title: "Project Title 9",
    slug: "project-title-9",
    tags: "Ruby on Rails, PostgreSQL",
    description: "A web application built with Ruby on Rails.",
    category: "web",
    images: [
      "./assets/images/sample1.png",
      "./assets/images/sample2.png",
      "./assets/images/sample3.png",
      "./assets/images/sample4.png",
      "./assets/images/sample5.png",
      "./assets/images/sample6.png",
    ],
    links: [
      { url: "#", icon: "fas fa-play-circle" },
      { url: "https://github.com/", icon: "fab fa-github" },
    ],
  },
  {
    title: "Project Title 10",
    slug: "project-title-10",
    tags: "Laravel, MySQL",
    description: "A web application built with Laravel and MySQL.",
    category: "web",
    images: [
      "./assets/images/sample1.png",
      "./assets/images/sample2.png",
      "./assets/images/sample3.png",
      "./assets/images/sample4.png",
      "./assets/images/sample5.png",
      "./assets/images/sample6.png",
    ],
    links: [
      { url: "#", icon: "fas fa-play-circle" },
      { url: "https://github.com/", icon: "fab fa-github" },
    ], 
  },
  {
    title: "Project Title 11",
    slug: "project-title-11",
    tags: "ASP.NET, SQL Server",
    description: "A web application built with ASP.NET and SQL Server.",
    category: "web",
    images: [
      "./assets/images/sample1.png",
      "./assets/images/sample2.png",
      "./assets/images/sample3.png",
      "./assets/images/sample4.png",
      "./assets/images/sample5.png",
      "./assets/images/sample6.png",
    ],
    links: [
      { url: "#", icon: "fas fa-play-circle" },
      { url: "https://github.com/", icon: "fab fa-github" },
    ],
  },
  {
    title: "Project Title 12",
    slug: "project-title-12",
    tags: "Flask, SQLite",
    description: "A web application built with Flask and SQLite.",
    category: "web",
    images: [
      "./assets/images/sample1.png",
      "./assets/images/sample2.png",
      "./assets/images/sample3.png",
      "./assets/images/sample4.png",
      "./assets/images/sample5.png",
      "./assets/images/sample6.png",
    ],
    links: [
      { url: "#", icon: "fas fa-play-circle" },
      { url: "https://github.com/", icon: "fab fa-github" },
    ],
  },
];
