/* =============================================
   Project Portfolio Data Template
   Replace sample values with your real projects
============================================= */

export const cardsData = [
  {
    title: "E-Commerce Platform",
    slug: "e-commerce-platform",
    tags: "React, Node.js, MongoDB, Stripe, Redux",
    description: "A comprehensive e-commerce solution with user authentication, payment processing, and admin dashboard. Features include product catalog, shopping cart, order management, and real-time inventory tracking. Built with modern technologies to ensure scalability and performance. Includes responsive design for optimal mobile experience. Supports multiple payment gateways and integrates with third-party services for shipping and analytics. Provides a seamless user experience with advanced search and filtering options.",
    category: "fullstack",
    images: [

    ],
    links: [
      { url: "#", icon: "fas fa-play-circle" },
      { url: "https://github.com/", icon: "fab fa-github" },
    ],
  },
  {
    title: "RESTful API Gateway",
    slug: "restful-api-gateway",
    tags: "Node.js, Express.js, Redis, JWT, Docker",
    description: "Scalable API gateway with authentication, rate limiting, and microservices integration. Handles request routing, load balancing, and API versioning for multiple backend services. Includes comprehensive logging, monitoring, and error handling mechanisms. Designed for high-traffic applications with robust security features.",
    category: "backend",
    images: [
      "./assets/images/sample1.png",
      "./assets/images/sample2.png",
      "./assets/images/sample3.png",
      "./assets/images/sample4.png",
      "./assets/images/sample5.png",
      "./assets/images/sample6.png",
    ],
    links: [
      { url: "#", icon: "fas fa-play-circle" },
      { url: "https://github.com/", icon: "fab fa-github" },
    ],
  },
  {
    title: "Portfolio Website",
    slug: "portfolio-website",
    tags: "React, TailwindCSS, Framer Motion, Vite",
    description: "Modern and responsive portfolio website showcasing projects and skills with smooth animations. Features dark/light theme toggle, contact form integration, and optimized performance. Built with accessibility in mind and SEO-friendly structure. Includes interactive elements and micro-animations for enhanced user experience.",
    category: "frontend",
    images: [
      "./assets/images/sample1.png",
      "./assets/images/sample2.png",
      "./assets/images/sample3.png",
      "./assets/images/sample4.png",
      "./assets/images/sample5.png",
      "./assets/images/sample6.png",
    ],
    links: [
      { url: "#", icon: "fas fa-play-circle" },
      { url: "https://github.com/", icon: "fab fa-github" },
    ],
  },
  {
    title: "Fitness Tracker App",
    slug: "fitness-tracker-app",
    tags: "React Native, Firebase, Health API, Redux",
    description: "Cross-platform fitness application with comprehensive workout tracking and nutrition logging. Features personalized workout plans, progress analytics, and social sharing capabilities. Integrates with health devices and wearables for accurate data collection. Includes gamification elements to motivate users in their fitness journey.",
    category: "mobile",
    images: [
      "./assets/images/sample1.png",
      "./assets/images/sample2.png",
      "./assets/images/sample3.png",
      "./assets/images/sample4.png",
      "./assets/images/sample5.png",
      "./assets/images/sample6.png",
    ],
    links: [
      { url: "#", icon: "fas fa-play-circle" },
      { url: "https://github.com/", icon: "fab fa-github" },
    ],
  },
  {
    title: "AI Image Recognition",
    slug: "ai-image-recognition",
    tags: "Python, TensorFlow, OpenCV, Flask, Docker",
    description: "Machine learning application for real-time image classification and object detection. Uses deep learning models trained on custom datasets for accurate recognition. Features web API for integration with other applications and batch processing capabilities. Includes model versioning and continuous learning from user feedback for improved accuracy.",
    category: "ai",
    images: [
      "./assets/images/sample1.png",
      "./assets/images/sample2.png",
      "./assets/images/sample3.png",
      "./assets/images/sample4.png",
      "./assets/images/sample5.png",
      "./assets/images/sample6.png",
    ],
    links: [
      { url: "#", icon: "fas fa-play-circle" },
      { url: "https://github.com/", icon: "fab fa-github" },
    ],
  },
  {
    title: "Learning Management System",
    slug: "learning-management-system",
    tags: "Next.js, Python, AI/ML, PostgreSQL, WebRTC",
    description: "Comprehensive learning platform with AI-powered personalized recommendations and virtual classroom features. Combines full-stack web development with machine learning for adaptive learning paths. Includes video conferencing, real-time collaboration tools, and intelligent content curation. Features mobile app companion and gamified learning experience.",
    category: "fullstack ai",
    images: [
      "./assets/images/sample1.png",
      "./assets/images/sample2.png",
      "./assets/images/sample3.png",
      "./assets/images/sample4.png",
      "./assets/images/sample5.png",
      "./assets/images/sample6.png",
    ],
    links: [
      { url: "#", icon: "fas fa-play-circle" },
      { url: "https://github.com/", icon: "fab fa-github" },
    ],
  },
  {
    title: "Social Media Dashboard",
    slug: "social-media-dashboard",
    tags: "Vue.js, Express.js, PostgreSQL, Socket.io",
    description: "Analytics dashboard for social media management with real-time data visualization and reporting. Provides comprehensive insights into user engagement, post performance, and audience demographics. Features automated content scheduling and multi-platform integration. Designed for marketing teams and social media managers.",
    category: "fullstack",
    images: [
      "./assets/images/sample1.png",
      "./assets/images/sample2.png",
      "./assets/images/sample3.png",
      "./assets/images/sample4.png",
      "./assets/images/sample5.png",
      "./assets/images/sample6.png",
    ],
    links: [
      { url: "#", icon: "fas fa-play-circle" },
      { url: "https://github.com/", icon: "fab fa-github" },
    ],
  },
  {
    title: "GraphQL Server",
    slug: "graphql-server",
    tags: "GraphQL, Apollo Server, MongoDB, Prisma",
    description: "High-performance GraphQL server with real-time subscriptions and optimized database queries. Features type-safe schema definitions, custom resolvers, and efficient data loading patterns. Includes authentication middleware, caching strategies, and comprehensive testing suite. Built for modern frontend applications requiring flexible data fetching.",
    category: "backend",
    images: [
      "./assets/images/sample1.png",
      "./assets/images/sample2.png",
      "./assets/images/sample3.png",
      "./assets/images/sample4.png",
      "./assets/images/sample5.png",
      "./assets/images/sample6.png",
    ],
    links: [
      { url: "#", icon: "fas fa-play-circle" },
      { url: "https://github.com/", icon: "fab fa-github" },
    ],
  },
  {
    title: "Weather App",
    slug: "weather-app",
    tags: "JavaScript, CSS3, OpenWeather API, PWA",
    description: "Progressive web application providing detailed weather information with location-based forecasts. Features 7-day forecast, hourly predictions, weather maps, and severe weather alerts. Includes offline functionality and push notifications for weather updates. Responsive design works seamlessly across all devices.",
    category: "frontend",
    images: [
      "./assets/images/sample1.png",
      "./assets/images/sample2.png",
      "./assets/images/sample3.png",
      "./assets/images/sample4.png",
      "./assets/images/sample5.png",
      "./assets/images/sample6.png",
    ],
    links: [
      { url: "#", icon: "fas fa-play-circle" },
      { url: "https://github.com/", icon: "fab fa-github" },
    ],
  },
  {
    title: "Chat Messenger",
    slug: "chat-messenger",
    tags: "Flutter, Dart, Socket.io, Firebase",
    description: "Real-time messaging application with end-to-end encryption and multimedia sharing. Features group chats, voice messages, file sharing, and message reactions. Includes push notifications, offline message sync, and customizable themes. Built with privacy and security as top priorities for user communication.",
    category: "mobile",
    images: [
      "./assets/images/sample1.png",
      "./assets/images/sample2.png",
      "./assets/images/sample3.png",
      "./assets/images/sample4.png",
      "./assets/images/sample5.png",
      "./assets/images/sample6.png",
    ],
    links: [
      { url: "#", icon: "fas fa-play-circle" },
      { url: "https://github.com/", icon: "fab fa-github" },
    ],
  },
  {
    title: "Task Management System",
    slug: "task-management-system",
    tags: "Angular, NestJS, MySQL, TypeScript",
    description: "Enterprise-level task management application with team collaboration features and project tracking. Includes kanban boards, time tracking, file sharing, and detailed reporting capabilities. Supports role-based access control and customizable workflows. Perfect for agile teams and project managers.",
    category: "fullstack",
    images: [
      "./assets/images/sample1.png",
      "./assets/images/sample2.png",
      "./assets/images/sample3.png",
      "./assets/images/sample4.png",
      "./assets/images/sample5.png",
      "./assets/images/sample6.png",
    ],
    links: [
      { url: "#", icon: "fas fa-play-circle" },
      { url: "https://github.com/", icon: "fab fa-github" },
    ],
  },
  {
    title: "Smart Home Automation",
    slug: "smart-home-automation",
    tags: "IoT, React Native, Node.js, MQTT, AI",
    description: "IoT-based smart home system with mobile app control and AI-driven automation. Features real-time monitoring of home devices, energy consumption analytics, and voice control integration. Supports multiple protocols for device communication and includes security features like motion detection and alerts. Designed for seamless user experience and energy efficiency.",
    category: "mobile ai",
    images: [
      "./assets/images/sample1.png",
      "./assets/images/sample2.png",
      "./assets/images/sample3.png",
      "./assets/images/sample4.png",
      "./assets/images/sample5.png",
      "./assets/images/sample6.png",
    ],
    links: [
      { url: "#", icon: "fas fa-play-circle" },
      { url: "https://github.com/", icon: "fab fa-github" },
    ],
  },
];